name: kiiss
channels:
  - pytorch-lts
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - cudatoolkit=11.1.74
  - ffmpeg=4.2.2
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - intel-openmp=2021.3.0
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libidn2=2.3.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libvpx=1.7.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - ncurses=6.2
  - nettle=3.7.3
  - ninja=1.10.2
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openh264=2.1.0
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - pillow=8.3.1
  - pip=21.0.1
  - python=3.7.11
  - pytorch=1.8.2
  - readline=8.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - torchaudio=0.8.2
  - torchvision=0.9.2
  - typing_extensions=3.10.0.2
  - wheel=0.37.0
  - x264=1!157.20191217
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==0.14.1
    - alembic==1.7.5
    - argcomplete==1.12.3
    - argon2-cffi==21.1.0
    - attrs==21.2.0
    - autopage==0.4.0
    - backcall==0.2.0
    - bleach==4.1.0
    - cachetools==4.2.4
    - cffi==1.14.6
    - charset-normalizer==2.0.6
    - cliff==3.9.0
    - cmaes==0.8.2
    - cmd2==2.3.2
    - colorlog==6.6.0
    - cycler==0.10.0
    - debugpy==1.4.3
    - decorator==5.1.0
    - defusedxml==0.7.1
    - entrypoints==0.3
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - greenlet==1.1.2
    - grpcio==1.41.0
    - idna==3.2
    - importlib-metadata==4.8.1
    - importlib-resources==5.4.0
    - ipykernel==6.4.1
    - ipython==7.28.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.18.0
    - jinja2==3.0.1
    - joblib==1.1.0
    - jsonschema==4.1.0
    - jupyter==1.0.0
    - jupyter-client==7.0.6
    - jupyter-console==6.4.0
    - jupyter-core==4.8.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - kiwisolver==1.3.2
    - mako==1.1.6
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib==3.4.3
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - nbclient==0.5.4
    - nbconvert==6.2.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.4
    - oauthlib==3.1.1
    - opencv-python==4.5.3.56
    - optuna==2.10.0
    - packaging==21.0
    - pandas==1.3.4
    - pandocfilters==1.5.0
    - parso==0.8.2
    - pbr==5.8.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prettytable==2.4.0
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.20
    - protobuf==3.18.0
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pygments==2.10.0
    - pyparsing==2.4.7
    - pyperclip==1.8.2
    - pyrsistent==0.18.0
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==6.0
    - pyzmq==22.3.0
    - qtconsole==5.1.1
    - qtpy==1.11.2
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scikit-learn==1.0.1
    - scipy==1.7.1
    - send2trash==1.8.0
    - sqlalchemy==1.4.27
    - stevedore==3.5.0
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - terminado==0.12.1
    - testpath==0.5.0
    - threadpoolctl==3.0.0
    - torchmetrics==0.5.1
    - torchsummary==1.5.1
    - tornado==6.1
    - tqdm==4.62.3
    - traitlets==5.1.0
    - urllib3==1.26.7
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.0.1
    - widgetsnbextension==3.5.1
    - zipp==3.6.0
